name: Flight Pipeline

on:
  schedule:
    - cron: "0 7 * * *"

  workflow_dispatch:

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Collect Bronze
        run: python collect_opensky.py
        env:
          OPENSKY_CLIENT_ID: ${{ secrets.OPENSKY_CLIENT_ID }}
          OPENSKY_CLIENT_SECRET: ${{ secrets.OPENSKY_CLIENT_SECRET }}
          CONNECT_STR: ${{ secrets.CONNECT_STR }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

      - name: Bronze to Prata
        run: python bronzetoprata.py
        env:
          CONNECT_STR: ${{ secrets.CONNECT_STR }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          CONTAINER_PRATA: ${{ secrets.CONTAINER_PRATA }}

      - name: Prata to Ouro
        run: python pratatoouro.py
        env:
          CONNECT_STR: ${{ secrets.CONNECT_STR }}
          CONTAINER_PRATA: ${{ secrets.CONTAINER_PRATA }}
          CONTAINER_OURO: ${{ secrets.CONTAINER_OURO }}

